// Code generated by mockery v1.0.0. DO NOT EDIT.

package extractors

import mock "github.com/stretchr/testify/mock"
import time "time"

// MockSleeper is an autogenerated mock type for the Sleeper type
type MockSleeper struct {
	mock.Mock
}

// Sleep provides a mock function with given fields: duration
func (_m *MockSleeper) Sleep(duration time.Duration) {
	_m.Called(duration)
}
