// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package extractors

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockSleeper is an autogenerated mock type for the Sleeper type
type MockSleeper struct {
	mock.Mock
}

// Sleep provides a mock function with given fields: duration
func (_m *MockSleeper) Sleep(duration time.Duration) {
	_m.Called(duration)
}
