// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package sitemap

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockLinkGenerator is an autogenerated mock type for the LinkGenerator type
type MockLinkGenerator struct {
	mock.Mock
}

// GenerateLinks provides a mock function with given fields: ctx, baseLink
func (_m *MockLinkGenerator) GenerateLinks(ctx context.Context, baseLink string) ([]string, error) {
	ret := _m.Called(ctx, baseLink)

	var r0 []string
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, baseLink)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, baseLink)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
