required = [
  "github.com/alecthomas/gometalinter",
  "github.com/vektra/mockery/cmd/mockery",
  "github.com/cweill/gotests/gotests",
]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.6.1"

[[constraint]]
  name = "github.com/go-log/log"
  version = "0.2.0"

[[constraint]]
  name = "github.com/thewizardplusplus/go-html-selector"
  version = "1.4.0"
