// Code generated by mockery v1.0.0. DO NOT EDIT.

package crawler

import mock "github.com/stretchr/testify/mock"

// MockErrorHandler is an autogenerated mock type for the ErrorHandler type
type MockErrorHandler struct {
	mock.Mock
}

// HandleError provides a mock function with given fields: err
func (_m *MockErrorHandler) HandleError(err error) {
	_m.Called(err)
}
