// Code generated by mockery v1.0.0. DO NOT EDIT.

package crawler

import context "context"
import mock "github.com/stretchr/testify/mock"

// MockLinkExtractor is an autogenerated mock type for the LinkExtractor type
type MockLinkExtractor struct {
	mock.Mock
}

// ExtractLinks provides a mock function with given fields: ctx, link
func (_m *MockLinkExtractor) ExtractLinks(ctx context.Context, link string) ([]string, error) {
	ret := _m.Called(ctx, link)

	var r0 []string
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, link)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, link)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
