// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package checkers

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/thewizardplusplus/go-crawler/models"
)

// MockLinkChecker is an autogenerated mock type for the LinkChecker type
type MockLinkChecker struct {
	mock.Mock
}

// CheckLink provides a mock function with given fields: ctx, link
func (_m *MockLinkChecker) CheckLink(ctx context.Context, link models.SourcedLink) bool {
	ret := _m.Called(ctx, link)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, models.SourcedLink) bool); ok {
		r0 = rf(ctx, link)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
