// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package handlers

import mock "github.com/stretchr/testify/mock"

// MockContextCancellerInterface is an autogenerated mock type for the ContextCancellerInterface type
type MockContextCancellerInterface struct {
	mock.Mock
}

// CancelContext provides a mock function with given fields:
func (_m *MockContextCancellerInterface) CancelContext() {
	_m.Called()
}
