// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package handlers

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	crawler "github.com/thewizardplusplus/go-crawler"
)

// MockLinkHandler is an autogenerated mock type for the LinkHandler type
type MockLinkHandler struct {
	mock.Mock
}

// HandleLink provides a mock function with given fields: ctx, link
func (_m *MockLinkHandler) HandleLink(ctx context.Context, link crawler.SourcedLink) {
	_m.Called(ctx, link)
}
