// Code generated by mockery v1.0.0. DO NOT EDIT.

package handlers

import context "context"
import crawler "github.com/thewizardplusplus/go-crawler"
import mock "github.com/stretchr/testify/mock"

// MockLinkHandler is an autogenerated mock type for the LinkHandler type
type MockLinkHandler struct {
	mock.Mock
}

// HandleLink provides a mock function with given fields: ctx, link
func (_m *MockLinkHandler) HandleLink(ctx context.Context, link crawler.SourcedLink) {
	_m.Called(ctx, link)
}
