// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package registers

import mock "github.com/stretchr/testify/mock"

// MockLinkGenerator is an autogenerated mock type for the LinkGenerator type
type MockLinkGenerator struct {
	mock.Mock
}

// GenerateLinks provides a mock function with given fields: baseLink
func (_m *MockLinkGenerator) GenerateLinks(baseLink string) ([]string, error) {
	ret := _m.Called(baseLink)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(baseLink)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(baseLink)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
